categories:
- Variant Analysis
description: Call genetic variants from next-generation DNA sequencing data
homepage_url: https://github.com/google/deepvariant
long_description: |
  DeepVariant is an analysis pipeline that uses a deep neural network to call genetic
  variants from next-generation DNA sequencing data.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/deepvariant
name: deepvariant
owner: iuc
type: unrestricted
